### ISSUE TITLE
New version for Angular 4

### ISSUE THREAD

**Issue by Arezoo-Bozorgmehr** [matsura/ng2-dual-list-box#22]
Hi,

this module dosn't work for Angular 4 project. I have installed it but i got an error about the false version;
ERROR in Metadata version mismatch for module ng2-dual-list-box.d.ts, found version 4, expected 3, resolving symbol AppModule inapp.module.ts, 

Could you help me please?
Best Regards

**Comment by deiyanfott** [comment]
@Arezoo-Bozorgmehr 

Seems the devDependencies in package.json already references Angular 5.
Will upgrading to Angular 5 have any issues on your project? If none, maybe you can update and try reinstalling the module.

**Comment by Arezoo-Bozorgmehr** [comment]
@deiyanfott 
thanks for your answer, but i'm working with angular 4 not 5. I want to use this module in my project for angular 4 but i've got that Error. How can i update it or something else. I'v tried with this command line npm uninstall ng2-dual-list-box --save
npm install ng2-dual-list-box@^4.0.0 --save
but didn't work.

**Comment by deiyanfott** [comment]
@Arezoo-Bozorgmehr 

npm install ng2-dual-list-box@^4.0.0 --save <-- you need to provide the version of the dual list box module not the angular version you are working on.

The most recent pre 1.2.x dual list box module version is 1.0.5.
You can try npm install ng2-dual-list-box@1.0.5 --save but there is no guarantee no issues will be encountered.

**Comment by Arezoo-Bozorgmehr** [comment]
@deiyanfott 
Thanks. That works. I'm searching also for a Treeview Component or Module. Could you suggest me somethings.

**Comment by deiyanfott** [comment]
@Arezoo-Bozorgmehr 

Not familiar but you may try ngx-treeview or angular-tree-component.

**Comment by Arezoo-Bozorgmehr** [comment]
@deiyanfott 
thanks alot for your information and help.

**Comment by sundertinwar** [comment]
I had used this component in my Angular 4 project in January. We are about to release this project. When I try to generate production build using
`ng build --prod --base-href /myproj/`
I get these warnings and control doesn't work in browser.
```
WARNING in ./src/$$_gendir/node_modules/ng2-dual-list-box/ng2-dual-list-box.ngfactory.ts
86:34-39 "export 'ɵa' (imported as 'i1') was not found in 'ng2-dual-list-box'
    at HarmonyImportSpecifierDependency._getErrors (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\TFS\LabSOR\LabSOR\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

WARNING in ./src/$$_gendir/node_modules/ng2-dual-list-box/ng2-dual-list-box.ngfactory.ts
86:57-62 "export 'ɵb' (imported as 'i1') was not found in 'ng2-dual-list-box'
    at HarmonyImportSpecifierDependency._getErrors (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\TFS\LabSOR\LabSOR\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
Below is the error I receive in browser console -
![image](https://user-images.githubusercontent.com/666107/39696741-44369fca-520c-11e8-9d8c-2521d76c0cad.png)

Any idea whats wrong where?
