### ISSUE TITLE
Error while generating production build.

### ISSUE THREAD

**Issue by sundertinwar** [matsura/ng2-dual-list-box#27]
Hi,

I has used this control in January in my Angular 4 project (version : 1.0.5). Currently we are about to release the project but I am getting warnings/errors while generating the build.
`ng build --prod --base-href /myproj/`

I am getting below warnings -
```
WARNING in ./src/$$_gendir/node_modules/ng2-dual-list-box/ng2-dual-list-box.ngfactory.ts
86:34-39 "export 'ɵa' (imported as 'i1') was not found in 'ng2-dual-list-box'
    at HarmonyImportSpecifierDependency._getErrors (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\TFS\LabSOR\LabSOR\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

WARNING in ./src/$$_gendir/node_modules/ng2-dual-list-box/ng2-dual-list-box.ngfactory.ts
86:57-62 "export 'ɵb' (imported as 'i1') was not found in 'ng2-dual-list-box'
    at HarmonyImportSpecifierDependency._getErrors (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:677:24)
    at Compilation.finish (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:535:9)
    at applyPluginsParallel.err (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compiler.js:512:17)
    at C:\TFS\LabSOR\LabSOR\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:481:11)
    at processModuleDependencies.err (C:\TFS\LabSOR\LabSOR\node_modules\webpack\lib\Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
After warnings if I deploy this build I am getting below errors in browser console and control not loading
![image](https://user-images.githubusercontent.com/666107/39696981-0cad091c-520d-11e8-85e9-de55ac8fd707.png)
Any idea why it is not working?

**Comment by sundertinwar** [comment]
I am not getting this errors while generating Dev (not compressed/uglyfy) build.

`ng build -e dev --base-herf /myproj/`

**Comment by Rajh** [comment]
+1
Did you manage to fix this @sundertinwar  ?
